app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: "%app_locales%"
    defaults:
        _locale: "%locale%"

homepage:
    path: /{_locale}
    requirements:
        _locale: "%app_locales%"
    defaults:
        _controller: FrameworkBundle:Template:template
        template: default/homepage.html.twig
        _locale: "%locale%"

api:
    resource: "."
    type: "api_platform"
    prefix: "/api"
